// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1Rz1R7z82fa3P0jZA5XTitXoV7xZCUIo',
    appId: '1:1078965242879:web:705cd3fbd6b1128748f5ca',
    messagingSenderId: '1078965242879',
    projectId: 'flutter-template-noti',
    authDomain: 'flutter-template-noti.firebaseapp.com',
    storageBucket: 'flutter-template-noti.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx6zgP4VN9euQNvLDK-o5HMx_T2OXU6l8',
    appId: '1:1078965242879:android:f5715684c4d09f3c48f5ca',
    messagingSenderId: '1078965242879',
    projectId: 'flutter-template-noti',
    storageBucket: 'flutter-template-noti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjcyf8jnLDOx9ukb8k9G-IQ-1xSc6aUk',
    appId: '1:1078965242879:ios:fd03690225840e5548f5ca',
    messagingSenderId: '1078965242879',
    projectId: 'flutter-template-noti',
    storageBucket: 'flutter-template-noti.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjcyf8jnLDOx9ukb8k9G-IQ-1xSc6aUk',
    appId: '1:1078965242879:ios:fd03690225840e5548f5ca',
    messagingSenderId: '1078965242879',
    projectId: 'flutter-template-noti',
    storageBucket: 'flutter-template-noti.appspot.com',
    iosBundleId: 'com.example.flutterTemplate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1Rz1R7z82fa3P0jZA5XTitXoV7xZCUIo',
    appId: '1:1078965242879:web:b4707fc2ee6d770148f5ca',
    messagingSenderId: '1078965242879',
    projectId: 'flutter-template-noti',
    authDomain: 'flutter-template-noti.firebaseapp.com',
    storageBucket: 'flutter-template-noti.appspot.com',
  );
}
